Transform: AWS::Serverless-2016-10-31
Resources:
  lambdaestudos:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: lambdaestudos
      CodeUri: src/Function
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 10
      Tracing: Active
  lambdaestudosLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${lambdaestudos}